cog_identify = [
    "Locate the common object present in these pictures.",
    "Spot the same object that appears across these remote sensing images.",
    "Identify the shared object visible in this series of remote sensing images.",
    "Find the identical object featured in the given remote sensing images.",
    "Determine the matching object appearing in these snapshots.",
    "Recognize the recurring object in these images.",
    "Pinpoint the consistent object seen in this set of remote sensing images.",
    "Discover the object that is present in all of these pictures.",
    "What is the overlapping object found in these remote sensing images?",
    "Highlight the same object visible across these pictures.",
    "Can you identify the object that is the same in each image?",
    "Identify the repeated object within these images.",
    "Which object can be found in all of these images?",
    "Spot the object common to these remote sensing images.",
    "Find the item that appears in every image provided.",
    "Locate the singular item present in all the images.",
    "What is the shared object evident in these visuals?",
    "Discover the object that remains the same in these images.",
    "Recognize the one object present across all of these pictures.",
    "Identify the object that is featured in all of these images.",
    "Determine the consistent item visible in the pictures.",
    "Locate the recurring object in this collection of remote sensing images.",
    "Spot the common object displayed in these images.",
    "What identical object can you find in these remote sensing images?",
    "Tell which object appears repeatedly in the given remote sensing images.",
    "Recognize the matching item evident in these series of images.",
    "Pinpoint the same object shown across these visuals.",
    "Identify the overlapping object depicted in every image here.",
    "Locate the identical item that can be seen in the remote sensing images provided.",
    "Find the repeated object visible in this gallery of images.",
    "Discover the same characteristic object in these pictures.",
    "Which item appears more than once in all of these remote sensing images?",
    "Identify the object that links all these images together.",
    "Spot the object constant throughout this group of remote sensing images.",
    "Determine the common thing that can be seen in every image.",
    "Recognize the feature shared by all the pictures shown.",
    "What recurring object stands out in these remote sensing images?",
    "Pinpoint the identical item that connects these remote sensing images.",
    "Highlight the object consistent in this series of snapshots.",
    "What is the single repeating object within all the visuals here?",
    "Spot the same characteristic object found in the given remote sensing images.",
    "Locate the object seen across multiple images in this set.",
    "Identify the shared subject of interest in the provided pictures.",
    "Discover the repeated object appearing in the various images.",
    "Recognize the thing that is identical among the given images.",
    "Which object remains constant in all the images presented?",
    "Look for the matching item visible throughout these images.",
    "Find the overlapping object existing in this set of visuals.",
    "Identify the object recurring in all of these images.",
    "Which item featured here connects each image together?",
    "Spot the object found in every single photograph here.",
    "Highlight the item that shows up in each provided picture.",
    "What is the identical element appearing in these snapshots?",
    "Determine the matching object repeated through the series.",
    "Locate the object visible in every one of these remote sensing images.",
    "Discover the item that is common across the presented remote sensing images.",
    "Which object do these remote sensing images have in common?",
    "Recognize the consistent thing seen in all the pictures displayed.",
    "Spot the same object that can be observed in this set of remote sensing images.",
    "What similar object exists in the images here?",
    "Identify the shared feature that exists across each snapshot.",
    "Locate the recurring element present in the group of visuals.",
    "Find the object visible throughout these images.",
    "Highlight the item identical in all of these remote sensing images.",
    "Discover the thing that appears in every photograph shown.",
    "Pinpoint the same object appearing in each picture provided.",
    "What repeated object unites all the visuals here?",
    "Spot the characteristic item visible multiple times in these images.",
    "Identify what identical thing can be located in these remote sensing images.",
    "Determine the recurring object seen throughout all the remote sensing images.",
    "Discover the shared element appearing within this set of visuals.",
    "What repeating item can be noticed in these images?",
    "Pinpoint the identical object that is visible in each image.",
    "Highlight the same object present in all the given snapshots.",
    "What object links all of the displayed remote sensing images together?",
    "Locate the repetitive element across all of these remote sensing images.",
    "Recognize the identical item appearing in every image shown.",
    "Spot the object common to every snapshot offered here.",
    "Determine the subject matching across each picture of the series.",
    "Which object appears consistent among all the images shared?",
    "Find the object that remains a constant in these visuals.",
    "Identify the recurring feature visible across these remote sensing images.",
    "Spot the item that can be seen in every photograph.",
    "Highlight the shared object appearing in the collection of images.",
    "Pinpoint the singular item repeated through all the visuals provided.",
    "Discover which object is always present in this set of pictures.",
    "Locate the element that connects these remote sensing images with one another.",
    "Can you identify the recurring thing visible across these snapshots?",
    "What is the matching object featured in each of these remote sensing images?",
    "Spot the detail that is the same for all the provided remote sensing images.",
    "Which identical item ties the remote sensing images in this series together?",
    "Recognize the common feature evident throughout these pictures.",
    "Determine what recurring object shows up in this group of remote sensing images.",
    "Find the matching thing among all the remote sensing images presented here.",
    "Locate the constant item seen repeatedly in this collection of visuals.",
    "Highlight what overlapping object is present in every single picture",
    "Discover which identical thing is visible across all these remote sensing images.",
    "Pinpoint the object that is consistent in this set of snapshots.",
    "Detect the matching element present in these visuals.",
    "Reveal the shared object featured in all of the remote sensing images.",
    "Look for the identical item that appears in these remote sensing images.",
    "Uncover the object found in all of the pictures.",
    "See which object is identical in these images.",
    "Detect what matching element every image contains.",
    "Observe the repeating structure visible in all pictures.",
    "Figure out what object remains consistent in these remote sensing images.",
    "Investigate the similarities to find the identical item.",
    "Trace the same feature visible across multiple remote sensing images.",
    "Unfold the matching pattern highlighted in the visuals.",
    "Seek the shared item linking these visuals together.",
    "Notice the key object these remote sensing images emphasize collectively.",
    "Ascertain the unchanging item common to all pictures.",
    "Trace what visible item ties all the pictures together.",
    "Detect the element that reappears uniformly in all these remote sensing images.",
    "Discern the recurring visual theme common in each image.",
    "Unearth the fixed visual feature identifiable across snapshots.",
    "Define the repeated feature captured among all remote sensing images.",
    "Examine the one object featured repeatedly here.",
    "Confirm which feature is uniformly depicted in pictures.",
    "Name the shared object in every image.",
]

cog_bbox = [
    "Locate this object in the image by providing its bounding box",
    "Locate it in the image using bounding box",
    "Identify the position of the object within the image by defining its bounding box.",
    "Provide me with the coordinates of its bounding box within the image.",
    "Share the bounding box details for it in the image.",
    "Let me know the bounding box parameters for it in the image.",
    "Give me the coordinates of its bounding box in the image.",
    "Could you specify the bounding box of it within the image?",
    "What are the coordinates of its bounding box in the image?",
    "Offer the bounding box information for it in the image.",
    "Please share the bounding box coordinates for it in the image.",
    "Specify the parameters of its bounding box in the image.",
    "Tell me the bounding box coordinates for it in the image.",
    "Present the bounding box details for it in the image.",
    "Where is its bounding box located in the image?",
    "Give me the location of its bounding box in the image.",
    "Can you explain the bounding box coordinates for it within the image?",
    "Let me know where its bounding box is in the image.",
    "Where can I find its bounding box in the image?",
    "Share the bounding box location for it within the image.",
    "Help me find the bounding box details for it in the image.",
    "Can you list the bounding box parameters for it in the image?",
]


if __name__ == "__main__":

    import random

    new_items = []
    change_items = random.sample(cog_identify, 50)
    for item in cog_identify:
        if item not in change_items:
            new_items.append(item)
        else:
            new_items.append(item.replace("images", "remote sensing images"))

    with open("temp.py", "w") as f:
        f.write("temp_list = [\n")
        for item in new_items:
            f.write(f'    "{item}",\n')
        f.write("]\n")
