DOTA_DIOR_SYNONYMS = {
    "plane": "airplane",
    "baseball-diamond": "baseball diamond",
    "basketball-court": "basketball court",
    "container-crane": "container crane",
    "ground-track-field": "ground track field",
    "large-vehicle": "vehicle",
    "small-vehicle": "vehicle",
    "soccer-ball-field": "soccer ball field",
    "storage-tank": "storage tank",
    "swimming-pool": "swimming pool",
    "tennis-court": "tennis court",
    "storagetank": "storage tank",
    "basketballcourt": "basketball court",
    "Expressway-service-area": "expressway service area",
    "baseballfield": "baseball diamond",
    "Expressway-toll-station": "expressway toll station",
    "golffield": "golf field",
    "groundtrackfield": "ground track field",
    "tenniscourt": "tennis court",
}

DOTA_DIOR_COMBINE = [
    "airport",
    "container crane",
    "tennis court",
    "airplane",
    "ship",
    "dam",
    "helicopter",
    "storage tank",
    "roundabout",
    "bridge",
    "chimney",
    "ground track field",
    "expressway toll station",
    "golf field",
    "overpass",
    "soccer ball field",
    "helipad",
    "Expressway-Service-area",
    "trainstation",
    "vehicle",
    "stadium",
    "basketball court",
    "harbor",
    "baseball diamond",
    "swimming pool",
    "windmill"
]