dg_compare = [
    "Carefully examine both images.",
    "Observe the two images thoroughly.",
    "Closely inspect the two images.",
    "Focus on both images.",
    "Review both images attentively.",
    "Compare the two remote sensing images.",
    "Note the differences in the images.",
    "Spot dissimilarities in the images.",
]

dg_describe = [
    "Carefully examine both images and note their difference in a brief sentence.",
    "Observe the two images thoroughly and summarize their changes in one short sentence.",
    "Closely inspect the two images and identify their difference in a single sentence.",
    "Inspect the images thoroughly and mention their subtle distinctions briefly.",
    "Focus on both images and deliver a brief description of the changes.",
    "Examine both sides with care and describe the changes noted in one sentence.",
    "Review both images attentively and detail their difference in a short phrase.",
    "Compare the two remote sensing images and describe the distinctions briefly.",
    "Highlight the differences you notice in the two images with a concise explanation.",
    "Provide a short summary distinguishing the two remote sensing images.",
    "Identify and describe, in brief, how the images are not the same.",
    "Point out the variations between the two remote sensing images with a simple description.",
    "Describe the contrasts between the two images with a short explanation.",
    "Offer a quick overview of how the two remote sensing images vary.",
    "Note the differences in the images and provide a brief clarification.",
    "Pinpoint the differences in the visuals and explain them succinctly.",
    "Provide a brief insight into what separates the second image from the first image.",
    "Elaborate briefly on the variations observed in the two remote sensing images.",
    "Spot dissimilarities in the images and summarize them quickly.",
    "Compare and outline their dissimilarities in a succinct form.",
    "Briefly state the contrasting details or elements in the two images.",
]

dg_describe_answer_disappear = [
    "<object> vanishes in the second image, as opposed to the first one.",
    "In comparison to the first image, <object> is missing in the second image.",
    "Compared to the first image, the second lacks <object>.",
    "The second image shows the absence of <object>, which can be seen in the first image.",
    "<object> that is present in the first image is not visible in the second image.",
    "In the second image, <object> is no longer visible",
    "From the first image to the second, <object> goes missing.",
    "<object> is absent in the second image, though it appears in the first.",
    "Compared to the first image, the second is missing <object>.",
    "<object> is missing from the second image but visible in the first one.",
    "Between the two images, <object> seems to disappear in the second.",
    "The second image no longer contains the <object> seen in the first.",
    "<object> vanishes between the first and second image.",
    "<object> disappears from view in the second image",
    "The second image does not have <object> that appears in the first image.",
    "Observing the two images, <object> disappears in the second.",
    "<object> seen in the first image is missing in the second image.",
    "Between the first and second image, <object> is gone.",
    "It seems <object> disappears in the second image",
    "<object> that exists in the first image does not appear in the second.",
    "<object> vanishes from the first image to the second image.",
]

dg_describe_answer_appear = [
    "The second image showcases <object>, which is not present in the first one.",
    "There is <object> in the second picture that is missing from the first one.",
    "In the second image, <object> can be seen while it does not appear in the first.",
    "<object> emerges in the second image",
    "The second image features <object>, absent in the first image.",
    "You can find <object> in the second image that is not in the first.",
    "The second one contains <object>.",
    "<object> is present in the second picture",
    "In comparison to the first image, the second has <object>.",
    "<object> is detected in the second image but is missing from the first.",
    "In the second image, <object> appears",
    "<object> can be seen in the second image",
    "The second picture reveals <object>, which the first does not show.",
    "There is <object> noticeable in the second image",
    "In contrast to the first picture, the second includes <object>.",
    "The second image displays <object> that is absent in the first.",
    "You can notice <object> in the second image that is not visible in the first.",
    "In comparison with the first image, the second one includes <object>.",
    "In the second image, <object> can be seen",
    "The second image depicts <object>, absent from the first one.",
]

dg_bbox = [
    "Provide me with the coordinates of the bounding box where the differences occur.",
    "Share the bounding box coordinates indicating the variations.",
    "Identify the location of the bounding box where changes are observed.",
    "Let me know the coordinates of the bounding box showing differences.",
    "Specify the bounding box coordinates where there is a discrepancy.",
    "Pinpoint the coordinates of the region where they differ.",
    "What are the coordinates of the bounding box in which they vary?",
    "Can you give the coordinates for the bounding box where the distinctions exist?",
    "Provide the bounding box coordinates for the location with variations.",
    "Please identify the bounding box coordinates showing the variances.",
    "Give the exact coordinates of the bounding box that differs.",
    "Highlight the coordinates using bounding box where they differ.",
]

dg_hallucination = [
    "The two images are identical.",
    "There is no difference between the two images.",
    "Both images are exactly the same.",
    "The two images show no difference.",
    "There is no observable difference in the two images."
]
