icg_identify = [
    "Identify the object in Region-",
    "What is the object shown in Region-",
    "Can you recognize the object in Region-?",
    "What item is visible in Region-?",
    "Can you specify the object in Region-?",
    "What object appears in Region-?",
    "Can you name the object found in Region-?",
    "What can be observed in Region-?",
    "What object is evident in Region-?",
    "What is the object located in Region-?",
]

icg_bbox = [
    "Locate this object in the image by providing its bounding box",
    "Locate it in the image using bounding box"
    "Identify the position of the object within the image by defining its bounding box.",
    "Provide me with the coordinates of its bounding box within the image.",
    "Share the bounding box details for it in the image.",
    "Let me know the bounding box parameters for it in the image.",
    "Give me the coordinates of its bounding box in the image.",
    "Could you specify the bounding box of it within the image?",
    "What are the coordinates of its bounding box in the image?",
    "Offer the bounding box information for it in the image.",
    "Please share the bounding box coordinates for it in the image.",
    "Specify the parameters of its bounding box in the image.",
    "Tell me the bounding box coordinates for it in the image.",
    "Present the bounding box details for it in the image.",
    "Where is its bounding box located in the image?",
    "Give me the location of its bounding box in the image.",
    "Can you explain the bounding box coordinates for it within the image?",
    "Let me know where its bounding box is in the image.",
    "Where can I find its bounding box in the image?",
    "Share the bounding box location for it within the image.",
    "Help me find the bounding box details for it in the image.",
    "Can you list the bounding box parameters for it in the image?",
]

icg_bbox_all_region = [
    "Locate the bounding box of each region in the source image.",
    "Identify the bounding box for each region in the source image.",
    "Provide the bounding box coordinates for each region in the source image.",
    "Share the bounding box details for each region in the source image.",
    "List the bounding box parameters for each region in the source image.",
    "Give me the bounding box information for each region in the source image.",
    "Specify the bounding box coordinates for each region in the source image.",
    "Tell me the bounding box details for each region in the source image.",
    "Present the bounding box coordinates for each region in the source image.",
    "Where are the bounding boxes located for each region in the source image?",
]
